name: publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: build
        run: |
          yarn install --freeze-lockfile
          yarn build

      - name: publish
        run: |
          echo $NPM_AUTH_TOKEN
          echo $NODE_AUTH_TOKEN
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
